### ISSUE TITLE
Apple Clang 14.0.0 build issues

### ISSUE THREAD

**Issue by adamjstewart** [iains/gcc-12-branch#10]
First of all, thanks for making this fork! I've been able to build several versions of this fork of GCC on M1 using Apple Clang 13.1.6. However, the recent release of Xcode 14, which comes with Apple Clang 14.0.0, seems to have introduced build issues:
```
ld: Assertion failed: (_file->_atomsArrayCount == computedAtomCount && "more atoms allocated than expected"), function parse, file macho_relocatable_file.cpp, line 2061.
collect2: error: ld returned 1 exit status
make[6]: *** [libstdc++.la] Error 1
make[5]: *** [all-recursive] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-stage1-target-libstdc++-v3] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```
Below is the full build log, split into 3 parts to get past GitHub's upload file size limits:

* [build-log-1.txt](https://github.com/iains/gcc-12-branch/files/9592644/build-log-1.txt)
* [build-log-2.txt](https://github.com/iains/gcc-12-branch/files/9592645/build-log-2.txt)
* [build-log-3.txt](https://github.com/iains/gcc-12-branch/files/9592646/build-log-3.txt)

Specifically, the patch I'm using is https://raw.githubusercontent.com/Homebrew/formula-patches/1d184289/gcc/gcc-12.2.0-arm.diff, which should hopefully be relatively up-to-date.

**Comment by adamjstewart** [comment]
Also, I should clarify, I don't actually know if this problem is specific to arm64 or if it also affects x86_64, so this may not be the right place to open this issue. If anyone has access to Xcode 14 on x86_64, I would love to know if the build succeeds or not.

**Comment by kencu** [comment]
looks a lot like https://github.com/iains/gcc-12-branch/issues/6

**Comment by adamjstewart** [comment]
Agreed, will close as duplicate.
