### ISSUE TITLE
possible to add gcc standalone builds to the release section?

### ISSUE THREAD

**Issue by DeveloperKev** [iains/gcc-12-branch#14]
Hi,
i think this repo is missing something, that is: the releases section. It cant be bad if we could get standard gcc standalone builds. just like @fxcoudert did. (sorry Coudert, i dont feel alive when u post bugs here)

and to install brew, it is time consuming, also tedious to get just one compiler which they dont post directly. 
thanks for the good work!

**Comment by fxcoudert** [comment]
What do you mean by _“standard gcc standalone builds”_? If you mean binaries, there are a lot of way to get those:
- [Homebrew](https://brew.sh), or MacPorts, or other distributions
- installers which I build and [post there](https://github.com/fxcoudert/gfortran-for-macOS/releases)

The focus of this repository is the open source code itself.

**Comment by DeveloperKev** [comment]
yeah, binaries.

@fxcoudert does your installer needs xcode command line tools to be installed? also does macos sdk comes with the os itself?

**Comment by fxcoudert** [comment]
> does your installer needs xcode command line tools to be installed?

Yes. The command-line tools are required for development on macOS, and need to be downloaded for Apple.

> does macos sdk comes with the os itself?

No, Apple distributes it with the command-line tools and with Xcode.

**Comment by DeveloperKev** [comment]
> > does your installer needs xcode command line tools to be installed?
> 
> Yes. The command-line tools are required for development on macOS, and need to be downloaded for Apple.
> 
> > does macos sdk comes with the os itself?
> 
> No, Apple distributes it with the command-line tools and with Xcode.

so, i;ve to install xcode command line tools first, then the installer

one more thing, how will i call g++? will i have to manually symlink it to higher than clang?

**Comment by simonjwright** [comment]
If you want C/C+/Ada, plus a lot of other Ada-related tools, see [here](https://github.com/simonjwright/distributing-gcc/releases).
The x86_64 builds use standard GCC, the aarch64 builds use this repo.

**Comment by DeveloperKev** [comment]
> What do you mean by _“standard gcc standalone builds”_? If you mean binaries, there are a lot of way to get those:
> 
> * [Homebrew](https://brew.sh), or MacPorts, or other distributions
> * installers which I build and [post there](https://github.com/fxcoudert/gfortran-for-macOS/releases)
> 
> The focus of this repository is the open source code itself.

how do i add your binaries to path?

**Comment by fxcoudert** [comment]
> how do i add your binaries to path?

Set your `PATH` variable to include the right directory: https://kb.iu.edu/d/acar

**Comment by DeveloperKev** [comment]
> Set your `PATH` variable to include the right directory: https://kb.iu.edu/d/acar

do i have to symlink it to higher than that of clang?

**Comment by DeveloperKev** [comment]
> If you want C/C+/Ada, plus a lot of other Ada-related tools, see [here](https://github.com/simonjwright/distributing-gcc/releases). The x86_64 builds use standard GCC, the aarch64 builds use this repo.

thanks, i appreciate.
one suggestion, plz try to remove unnecessary tools and focus on c++

**Comment by iains** [comment]
"unnecessary" means what? -- if you mean that you are not interested in them, please consider that other people **are** interested
(FWIW I am a WG21 member, so obviously work on c++).

**Comment by DeveloperKev** [comment]
> "unnecessary" means what? -- if you mean that you are not interested in them, please consider that other people **are** interested (FWIW I am a WG21 member, so obviously work on c++).

i mean for the sake of space, and specific people. but there will be differences.

**Comment by DeveloperKev** [comment]
@iains u forgot to answer the issue.

**Comment by iains** [comment]
I do not plan (at this time) in producing binaries for GCC-12, as seen above there are other folks doing that. 

Actually, I do plan on producing a bootstrap toolchain based on GCC 10.4 at some stage, since that is the last version that can be built directly using system tools on all supported versions of OS X / macOS.

**Comment by simonjwright** [comment]
> > If you want C/C+/Ada, plus a lot of other Ada-related tools, see [here](https://github.com/simonjwright/distributing-gcc/releases). The x86_64 builds use standard GCC, the aarch64 builds use this repo.
> 
> thanks, i appreciate. one suggestion, plz try to remove unnecessary tools and focus on c++

Why would I want to do that? since (clearly) my main focus is Ada.

**Comment by DeveloperKev** [comment]
@simonjwright it doesnt mean, u cant do separate builds. 
i am saying the installer is big in size.
