### ISSUE TITLE
NEED gfortran-Intel-12.2-Ventura | Mac OS 13

### ISSUE THREAD

**Issue by Ilovecodinghaha** [iains/gcc-12-branch#16]
Hi everyone,

I'm new to Fortran and need gfortran-Intel-12.2-Ventura.dmg for Intel-based computers (OS 13).
But it still hasn't been released, so can I use the old version of gfortran for my Mac OS 13?

x86_64-apple-darwin22.2.0
Version 13.1 

Many many thanks

**Comment by Ilovecodinghaha** [comment]
Can I get some help here, please @fxcoudert @iains

**Comment by fxcoudert** [comment]
I will do it at some point, but my time is limited. You can use Homebrew in the meantime.

**Comment by mathstuf** [comment]
You can grab our builds from here: https://gitlab.kitware.com/utils/ci-utilities/-/releases/gfortran-macos%2Fv12.2-darwin-r0-20220922.0

It works on our 13.x machines, but we target 10.something IIRC.
