### ISSUE TITLE
is mieee-fp supported with arm64?

### ISSUE THREAD

**Issue by chengdang** [iains/gcc-12-branch#20]
Hello, thank you for making this package available. 

I'm trying to compile a fortran model on macOS Ventura (macOS 13, M2 chip), with GCC 12.2 Arm (downloaded here https://github.com/fxcoudert/gfortran-for-macOS/releases, and/or installed with homebrew)

It seem mieee-fp is not supported in this environment? Is there a new flag equivalent to mieee-fp? Thank you!

```
gfortran: error: unrecognized command-line option '-mieee-fp'
configure:1992: $? = 1
configure:2030: result: no
configure: failed program was:
|       program main
|
|       end
configure:2035: error: in ‘$path’:
configure:2037: error: Fortran compiler cannot create executables
See `config.log' for more details
```

**Comment by fxcoudert** [comment]
Why do you want to pass this option? `-mieee-fp` had two effects:
- on code generation (where is now is the default in most configurations, anyway)
- on linking with `-lieee`, but only on old GCC versions

On recent GCC, `-mieee-fp` is a no-op.
See the discussion at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84829 for full details.

**Comment by chengdang** [comment]
Thank you for your reply! I'll read more about this.
This is a legacy flag that perhaps can be removed.
