### ISSUE TITLE
12.2?

### ISSUE THREAD

**Issue by ilg-ul** [iains/gcc-12-branch#4]
GCC 12.2.0 was just released. Any estimate when you'll have time to update this branch?

**Comment by iains** [comment]
release 0...
https://github.com/iains/gcc-12-branch/releases/tag/gcc-12.2-darwin-r0

**Comment by ilg-ul** [comment]
Great, thank you!

I'll wait for @fxcoudert to update HomeBrew.

**Comment by ilg-ul** [comment]
BTW, any chance for these changes to be part of upstream 13.x, or the next target is 14.x?
