### ISSUE TITLE
build commands in docs format

### ISSUE THREAD

**Issue by DeveloperKev** [iains/gcc-12-branch#8]
Hi,
i was wondering if its possible to attach build commands also. 
How is it done in workflows? i'm curious. 
thanks for the good work!

**Comment by DeveloperKev** [comment]
@fxcoudert @iains @mathstuf can i get some help here

**Comment by iains** [comment]
The branches here are configured/built in the same way as upstream GCC .. 

 see, for example:
https://gcc.gnu.org/install/

(you will need Xcode [or, more easy, the Xcode command line tools] installed to build on macOS)

**Comment by DeveloperKev** [comment]
`contrib/download_prerequisites` will install the required packages, right?
another thing: this repos patches for arm64 is not officially provided by gnu, if i'm not wrong.
i checked the docs before, its kinda a manual. so i was expecting, a simplified one for apple silicon. A repo without this is sort of incomplete. hope u'll understand.

**Comment by DeveloperKev** [comment]
`"gmp","isl","libmpc","mpfr","zstd"`
are these dependencies needed after installing?

**Comment by fxcoudert** [comment]
- I have a series of build steps documented here: https://github.com/fxcoudert/gfortran-for-macOS/blob/master/build_package.md
- The dependencies (gmp, mpfr, mpc, isl, zstd) are needed at runtime, yes
- If you use `contrib/download_prerequisites` they will be downloaded and built automatically during the GCC build. If you do that, there is no external dependency beyond command-line tools (or Xcode)

**Comment by DeveloperKev** [comment]
will the dependencies (gmp, mpfr, mpc, isl, zstd) be included in gcc folder? or more like separately stored alongside `gcc` folder?

**Comment by iains** [comment]
you can build them
 1/ separately, either as shared libraries (or convenience) and provide --with-gmp= ... etc to tell the configure where to find them.
 2/ in-tree (sources at the same level as GCC) and then they will be bootstrapped along with the compiler.

If you use (1) and the convenience library method, or (2) - then there are no runtime dependencies (personally, I prefer that so I use method 2)

**Comment by DeveloperKev** [comment]
@iains so this repo has the required patches  for apple silicon that gnu still doesnt support?

@fxcoudert one thing for arm: `--build=aarch64-apple-darwin` will work?
i just love the work.

**Comment by DeveloperKev** [comment]
coudert, can u add an arm section in the doc, or update to make it more convenient

**Comment by iains** [comment]
> @iains so this repo has the required patches for apple silicon that gnu still doesnt support?

These are my development branches for the arm64 (aarch64) port, as and when I have spare time, and features are sufficiently 'finished' then they are upstreamed.. this all takes a lot of time (so it goes slowly when done as a hobby)
 
> @fxcoudert one thing for arm: `--build=aarch64-apple-darwin` will work? i just love the work.

I would recommend to use ```--build=aarch64-apple-darwin20``` or ```--build=aarch64-apple-darwin21 ```  (depending on the OS you are on) the configure process does make choices based on the OS version being targeted.

**Comment by DeveloperKev** [comment]
may i ask what do u mean by `development branches` ? doesnt gnu provide support for silicon mac? and what are the differences?
u must love gcc more than i do.

**Comment by iains** [comment]
please take a little time to find out how things work :)

Nothing happens by magic; unless someone pays for it (which they are not doing for arm64 on darwin) then the work is done by volunteers ...

**Comment by DeveloperKev** [comment]
thanks for clearing my doubts and the good work :)

**Comment by DeveloperKev** [comment]
@iains where do u post `gcc` builds?
another thing about the build target: is it possible to target all silicon mac? if, then what would be the ultimate build target? the latest the better?

**Comment by iains** [comment]
> @iains where do u post `gcc` builds?

I do not (often) post builds - mostly this work is taken by Home-brew and macports, who are the main distributors for macOS open source (there are some other folks who do it - but HB and macports are the main ones).

> another thing about the build target: is it possible to target all silicon mac? if, then what would be the ultimate build target? the latest the better?

Other way around - if you want to target darwin20 (macOS 11) and darwin21 (macOS 12) and the latest to be released, then you build for darwin20 (the earliest).  Backwards compatibility is provided by most systems (to some extent, but usually quite effectively for macOS) but forwards compatibility is hard/impossible to achieve since one cannot predict future changes.

**Comment by simonjwright** [comment]
> you can build them 1/ separately, either as shared libraries (or convenience) and provide --with-gmp= ... etc to tell the configure where to find them. 2/ in-tree (sources at the same level as GCC) and then they will be bootstrapped along with the compiler.
> 
> If you use (1) and the convenience library method, or (2) - then there are no runtime dependencies (personally, I prefer that so I use method 2)

I build in-tree, but one of the packages I release with the compiler needs the dylib for GMP, so I build that afterwards using the new compiler and the in-tree source and install over the compiler.

**Comment by iains** [comment]
I am going to close this, since "how to build GCC" is not specific to any of the development branches here.
